# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6edae144eff205b1bc859f2536b2c310312913863abc5a359d32df0e542254a372cb1e8e4e48a4bae1a2f17bee04b651a3b4bb4d254d634a9423e848c29d617

test:
  secret_key_base: 74714f3a2f903e84d2e437673dfb21441026943d6d0c130475faa03ca2d72bca885fe1f5263508e7e2a7a80e871fe13667004e566d3f85d5ffc547a2bb0aa1c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
